@url=http://localhost:4000/
@json = Content-Type: application/json

###
get {{url}}

###
get {{url}}api/users


###
post {{url}}

### 注册
post {{url}}api/register
{{json}}

{
    "username":"user1",
    "email":"user123@use.com",
    "password":"123456",
    "mobile":"15485625478",
    "rolelist":["chair","author"],
    "interest":"AI"

}
###"mobile":"18523425165",
###"interest_area":"AI"

### 登录
post {{url}}api/login
{{json}}

{
    "email":"admin1255@adm.com",
    "password":"123dsaf56"

}

###
get {{url}}api/adminPermis


###
post {{url}}api/adminPermis
{{json}}

{
    "name": "文章管理",
    "children": [
        {
            "name": "文章列表"
        }
    ]
}

###
get {{url}}api/chairPermiss


###
post {{url}}api/chairPermiss
{{json}}

{
    "name": "文章管理",
    "children": [
        {
            "name": "文章列表"
        },
        {
            "name": "提交文章"
        },
        {
            "name": "审核分配"
        }
    ]
}

###
get {{url}}api/authorPermiss


###
post {{url}}api/authorPermiss
{{json}}

{
    "name": "文章管理",
    "children": [
        {
            "name": "文章列表"
        },
        {
            "name": "提交文章"
        }
    ]
}

###
get {{url}}api/reviewerPermiss


###
post {{url}}api/reviewerPermiss
{{json}}

{
    "name": "文章管理",
    "children": [
        {
            "name": "文章列表"
        },
        {
            "name": "审核文章"
        }
    ]
}

###

get {{url}}api/permission?role=admin


