@url=http://localhost:4000/api/
@json = Content-Type: application/json

###
get {{url}}

###
get {{url}}users

### 注册
post {{url}}register
{{json}}

{
    "username":"user2",
    "email":"user233@use.com",
    "password":"123456",
    "mobile":"15485625478",
    "rolelist":["chair","reviewer"],
    "interest":"AI"

}

### 登录
post {{url}}login
{{json}}

{
    "email":"admin1255@adm.com",
    "password":"123456"

}

###
get {{url}}adminPermis


###
post {{url}}adminPermis
{{json}}

{
    "name": "文章管理",
    "children": [
        {
            "name": "文章列表"
        }
    ]
}

###
get {{url}}chairPermiss


###
post {{url}}chairPermiss
{{json}}

{
    "name": "文章管理",
    "children": [
        {
            "name": "文章列表"
        },
        {
            "name": "提交文章"
        },
        {
            "name": "审核分配"
        }
    ]
}

###
get {{url}}authorPermiss


###
post {{url}}authorPermiss
{{json}}

{
    "name": "文章管理",
    "children": [
        {
            "name": "文章列表"
        },
        {
            "name": "提交文章"
        }
    ]
}

###
get {{url}}reviewerPermiss


###
post {{url}}reviewerPermiss
{{json}}

{
    "name": "文章管理",
    "children": [
        {
            "name": "文章列表"
        },
        {
            "name": "审核文章"
        }
    ]
}

###

get {{url}}permission?role=admin

###
get {{url}}roles

###
post {{url}}roles
{{json}}

{
    "rolename":"reviewer",
    "description":"Paper reviewer"
}

###
get {{url}}profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmJlZTFiZDhjZjVkNmRhNWE4OWFlNiIsImlhdCI6MTY1MTUxMjc2NH0.Hfza97YxHYg8OocK05uPi4XVg7Mc4wTIvhJMe-yQm90